export const compareCopy = {
  "fr": {
    "nav": "Comparer",
    "title": "Deux histoires. Un monde.",
    "intro": "Mettez deux événements en regard. Comparez leurs dates, leurs lieux et ce qu’ils ont changé, puis revenez aux références.",
    "left": "Première histoire",
    "right": "Seconde histoire",
    "swap": "Inverser les histoires",
    "share": "Copier le lien",
    "copied": "Lien copié.",
    "copyFailed": "La copie automatique est indisponible. Copiez le lien ci-dessous.",
    "url": "Lien de cette comparaison",
    "sameEra": "Même période de navigation",
    "differentEra": "Périodes différentes",
    "note": "Les rapprochements invitent à comparer. Ils ne prouvent pas un lien causal. Les périodes sont des repères conventionnels, pas des chronologies universelles.",
    "pick": "Quelques points de départ",
    "date": "Date / période",
    "place": "Lieu / région",
    "what": "Ce qui se passe",
    "impact": "Ce qui change",
    "source": "Référence",
    "open": "Lire l’histoire complète",
    "cta": "Croisez les perspectives",
    "ctaText": "Une révolution en Europe, une transformation ailleurs. Découvrez les différences entre deux histoires choisies.",
    "presets": [
      "Écritures & États",
      "Empires anciens",
      "Villes & échanges",
      "Océans & idées",
      "Révolutions",
      "Indépendance & démocratie"
    ]
  },
  "en": {
    "nav": "Compare",
    "title": "Two stories. One world.",
    "intro": "Put two events side by side. Compare their dates, places and significance, then return to the references.",
    "left": "First story",
    "right": "Second story",
    "swap": "Swap stories",
    "share": "Copy link",
    "copied": "Link copied.",
    "copyFailed": "Automatic copying is unavailable. Copy the link below.",
    "url": "Link to this comparison",
    "sameEra": "Same navigation period",
    "differentEra": "Different periods",
    "note": "These pairings invite comparison. They do not establish a causal connection. Periods are conventional guides, not universal chronologies.",
    "pick": "A few starting points",
    "date": "Date / period",
    "place": "Place / region",
    "what": "What happens",
    "impact": "What changes",
    "source": "Reference",
    "open": "Read the full story",
    "cta": "Cross perspectives",
    "ctaText": "A revolution in Europe, a transformation elsewhere. Discover the differences between two selected stories.",
    "presets": [
      "Writing & states",
      "Ancient empires",
      "Cities & exchange",
      "Oceans & ideas",
      "Revolutions",
      "Independence & democracy"
    ]
  },
  "ar": {
    "nav": "قارن",
    "title": "قصتان. عالم واحد.",
    "intro": "ضع حدثين جنباً إلى جنب، وقارن تواريخهما وأماكنهما وتأثيرهما، ثم عد إلى المراجع.",
    "left": "القصة الأولى",
    "right": "القصة الثانية",
    "swap": "تبديل القصتين",
    "share": "نسخ الرابط",
    "copied": "تم نسخ الرابط.",
    "copyFailed": "النسخ التلقائي غير متاح. انسخ الرابط أدناه.",
    "url": "رابط هذه المقارنة",
    "sameEra": "فترة تصفح واحدة",
    "differentEra": "فترتان مختلفتان",
    "note": "تدعو هذه المقارنات إلى التأمل ولا تثبت علاقة سببية. الفترات أدوات اصطلاحية وليست تسلسلات زمنية موحدة لكل الحضارات.",
    "pick": "نقاط انطلاق مقترحة",
    "date": "التاريخ / الفترة",
    "place": "المكان / المنطقة",
    "what": "ما الذي يحدث؟",
    "impact": "ما الذي يتغير؟",
    "source": "المرجع",
    "open": "اقرأ القصة كاملة",
    "cta": "تقاطع وجهات النظر",
    "ctaText": "ثورة في أوروبا وتحول في منطقة أخرى. اكتشف الفروق بين قصتين مختارتين.",
    "presets": [
      "الكتابة والدول",
      "إمبراطوريات قديمة",
      "المدن والتبادل",
      "المحيطات والأفكار",
      "الثورات",
      "الاستقلال والديمقراطية"
    ]
  }
} as const;
