export const journeyCopy = {
  "fr": {
    "navJourney": "Voyage",
    "voyage": "VOYAGE DANS LE TEMPS",
    "hint": "Déplacez le temps. Découvrez le monde.",
    "start": "Entrer dans l’histoire",
    "atlas": "Le monde à cette époque.",
    "atlasText": "Changez d’époque, puis choisissez une région. Les repères indiquent des régions, pas les lieux exacts des événements.",
    "chapter": "CHAPITRE",
    "read": "Vivre cette histoire",
    "prev": "Reculer dans le temps",
    "next": "Avancer dans le temps",
    "play": "Lancer le voyage",
    "pause": "Mettre en pause",
    "year": "Aller à une année",
    "jump": "Voyager",
    "range": "Parcourir les événements",
    "invalid": "Entrez une année entière, différente de zéro, entre −298000 et 2026.",
    "jumpNote": "Le voyage rejoint l’événement sélectionné le plus proche. Pas d’échelle temporelle proportionnelle.",
    "elsewhere": "Pendant ce temps…",
    "empty": "Aucun événement sélectionné dans cette région à cette époque.",
    "archive": "Explorer cette région",
    "chapters": "Six époques. Une aventure.",
    "chaptersText": "Choisissez votre point de départ. Chaque époque ouvre une fenêtre sur un monde différent.",
    "ai": "Vision artistique générée par IA · pas une archive",
    "map": "Carte : côtes actuelles, Natural Earth. Repères régionaux indicatifs.",
    "open": "Ouvrir le chapitre",
    "what": "Ce qui s’est passé",
    "why": "Ce que cela a changé",
    "source": "Revenir aux sources",
    "selection": "L’histoire a plusieurs centres.",
    "selectionText": "Des récits sur tous les continents. Des dates, des références et des perspectives pour comprendre les liens, sans réduire le monde à une seule chronologie.",
    "selected": "Sélection",
    "back": "Retour au voyage",
    "progress": "DANS CETTE HISTOIRE",
    "current": "Événement choisi",
    "browse": "Toutes les histoires",
    "years": "Des origines à 2026",
    "near": "Proximité dans le temps, pas nécessairement relation de cause à effet."
  },
  "en": {
    "navJourney": "Journey",
    "voyage": "A JOURNEY THROUGH TIME",
    "hint": "Move through time. Discover the world.",
    "start": "Step into history",
    "atlas": "The world in this era.",
    "atlasText": "Change the era, then choose a region. Markers represent regions, not precise event locations.",
    "chapter": "CHAPTER",
    "read": "Step into this story",
    "prev": "Travel back in time",
    "next": "Travel forward in time",
    "play": "Play the journey",
    "pause": "Pause the journey",
    "year": "Go to a year",
    "jump": "Travel",
    "range": "Browse events",
    "invalid": "Enter a whole year other than zero, from −298000 to 2026.",
    "jumpNote": "The journey goes to the nearest selected event. This is not a proportional time scale.",
    "elsewhere": "Meanwhile…",
    "empty": "No selected event in this region during this era.",
    "archive": "Explore this region",
    "chapters": "Six eras. One adventure.",
    "chaptersText": "Choose your starting point. Every era opens a window onto a different world.",
    "ai": "AI-generated artistic vision · not an archive",
    "map": "Map: present-day coastlines, Natural Earth. Indicative regional markers.",
    "open": "Open the chapter",
    "what": "What happened",
    "why": "What it changed",
    "source": "Back to the sources",
    "selection": "History has many centres.",
    "selectionText": "Stories across every continent. Dates, references and perspectives to understand connections, without reducing the world to a single chronology.",
    "selected": "Selection",
    "back": "Back to the journey",
    "progress": "IN THIS STORY",
    "current": "Selected event",
    "browse": "All stories",
    "years": "From our origins to 2026",
    "near": "Nearby in time, not necessarily connected by cause and effect."
  },
  "ar": {
    "navJourney": "الرحلة",
    "voyage": "رحلة عبر الزمن",
    "hint": "غيّر الزمن. اكتشف العالم.",
    "start": "ادخل إلى التاريخ",
    "atlas": "العالم في هذا العصر.",
    "atlasText": "اختر العصر ثم المنطقة. العلامات تمثل مناطق وليست مواقع دقيقة للأحداث.",
    "chapter": "الفصل",
    "read": "ادخل إلى هذه القصة",
    "prev": "العودة في الزمن",
    "next": "التقدم في الزمن",
    "play": "تشغيل الرحلة",
    "pause": "إيقاف الرحلة مؤقتاً",
    "year": "انتقل إلى سنة",
    "jump": "انطلق",
    "range": "تصفح الأحداث",
    "invalid": "أدخل سنة صحيحة غير صفر بين −298000 و2026.",
    "jumpNote": "تصل الرحلة إلى أقرب حدث مختار. التباعد ليس مقياساً زمنياً تناسبياً.",
    "elsewhere": "في هذه الأثناء…",
    "empty": "لا يوجد حدث مختار في هذه المنطقة خلال هذا العصر.",
    "archive": "استكشف هذه المنطقة",
    "chapters": "ستة عصور. مغامرة واحدة.",
    "chaptersText": "اختر نقطة البداية. كل عصر يفتح نافذة على عالم مختلف.",
    "ai": "تصور فني مولد بالذكاء الاصطناعي · ليس أرشيفاً",
    "map": "الخريطة: سواحل حالية من Natural Earth. علامات إقليمية تقريبية.",
    "open": "افتح الفصل",
    "what": "ما الذي حدث؟",
    "why": "ما الذي تغير؟",
    "source": "العودة إلى المراجع",
    "selection": "للتاريخ مراكز متعددة.",
    "selectionText": "قصص من كل القارات، مع تواريخ ومراجع وزوايا تساعد على فهم الروابط دون اختزال العالم في تسلسل واحد.",
    "selected": "مختارات",
    "back": "العودة إلى الرحلة",
    "progress": "في هذه القصة",
    "current": "الحدث المختار",
    "browse": "كل القصص",
    "years": "من البدايات إلى 2026",
    "near": "تقارب زمني لا يعني بالضرورة علاقة سببية."
  }
} as const;
