export const premiumCopy = {
  "fr": {
    "title": "Tout un monde.",
    "italic": "À travers le temps.",
    "intro": "Des origines à aujourd’hui. Explorez les histoires qui ont changé notre monde.",
    "start": "Commencer le voyage",
    "eras": "Choisissez votre époque.",
    "erasIntro": "Six portes d’entrée. Des milliers d’années à découvrir.",
    "galleryPrev": "Époques précédentes",
    "galleryNext": "Époques suivantes",
    "featured": "À découvrir",
    "mapInfo": "À propos de la carte",
    "filters": "Affiner la recherche",
    "mapIntro": "Un monde. Plusieurs histoires.",
    "atlasIntro": "Choisissez une région pour découvrir ses événements à cette époque.",
    "footer": "Le passé ouvre de nouveaux horizons.",
    "footerNote": "Une sélection mondiale, en trois langues.",
    "era": "Changer d’époque",
    "scroll": "Explorer les époques",
    "signature": "UNE CHRONIQUE VIVANTE"
  },
  "en": {
    "title": "One world.",
    "italic": "Across time.",
    "intro": "From our origins to today. Explore the stories that changed our world.",
    "start": "Begin the journey",
    "eras": "Choose your era.",
    "erasIntro": "Six starting points. Thousands of years to discover.",
    "galleryPrev": "Previous eras",
    "galleryNext": "Next eras",
    "featured": "In the spotlight",
    "mapInfo": "About the map",
    "filters": "Refine your search",
    "mapIntro": "One world. Many stories.",
    "atlasIntro": "Choose a region to discover its events in this era.",
    "footer": "The past opens new horizons.",
    "footerNote": "A worldwide selection, in three languages.",
    "era": "Change era",
    "scroll": "Explore the eras",
    "signature": "A LIVING CHRONICLE"
  },
  "ar": {
    "title": "عالم واحد.",
    "italic": "عبر الزمن.",
    "intro": "من البدايات إلى اليوم. اكتشف القصص التي غيّرت عالمنا.",
    "start": "ابدأ الرحلة",
    "eras": "اختر عصرك.",
    "erasIntro": "ست بوابات وآلاف السنين للاكتشاف.",
    "galleryPrev": "العصور السابقة",
    "galleryNext": "العصور التالية",
    "featured": "للاكتشاف",
    "mapInfo": "عن الخريطة",
    "filters": "تخصيص البحث",
    "mapIntro": "عالم واحد. قصص متعددة.",
    "atlasIntro": "اختر منطقة لاكتشاف أحداثها في هذا العصر.",
    "footer": "الماضي يفتح آفاقاً جديدة.",
    "footerNote": "مختارات عالمية بثلاث لغات.",
    "era": "غيّر العصر",
    "scroll": "اكتشف العصور",
    "signature": "حكاية حيّة"
  }
} as const;
