import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { events, isLanguage } from "@/lib/history";
import { copy } from "@/lib/i18n";
import { EventCard } from "@/components/event-card";
export default async function Home({params}: {params: Promise<{lang: string}>}) {
 const {lang} = await params; if (!isLanguage(lang)) notFound(); const t=copy[lang]; const featured=events[1];
 return <main id="content"><section className="hero container"><div className="hero-top"><div><p className="eyebrow line-label">{t.kicker}</p><h1>{t.title}<br/><em>{t.italic}</em></h1><p className="hero-description">{t.intro}</p><div className="hero-actions"><Link className="button primary" href={`/${lang}/explorer`}>{t.start} <span aria-hidden="true">↗</span></Link><Link className="button" href={`/${lang}/events/volubilis`}>{t.discover}</Link></div></div><div className="hero-date" aria-hidden="true"><span>789</span><small>ATAR / 001</small></div></div>
 <Link className="hero-image" href={`/${lang}/events/volubilis`}><Image src="/images/volubilis.webp" alt={events[0].title[lang]} width={1376} height={768} preload sizes="(max-width: 1200px) 100vw, 1200px"/><div className="hero-caption"><span className="eyebrow">VOLUBILIS / {events[0].date[lang]}</span><h2>{events[0].title[lang]}</h2><span aria-hidden="true">↗</span></div></Link><p className="image-note">{t.imageNote}</p>
 <div className="mini-timeline">{events.map(e => <Link key={e.slug} href={`/${lang}/events/${e.slug}`}><span className="timeline-dot"/><span dir="ltr">{e.date[lang]}</span><small>{e.place[lang]}</small></Link>)}</div></section>
 <section id="eras" className="section container"><div className="section-heading"><div><p className="eyebrow">ATAR / COLLECTION</p><h2>{t.eraTitle}</h2></div><p>{t.eraIntro}</p></div><div className="era-grid">{(['ancient','medieval','modern','contemporary'] as const).map((era,i) => <Link className="era-card" key={era} href={`/${lang}/explorer?era=${era}`}><span className="eyebrow">0{i+1}</span><h3>{t[era]}</h3><span className="era-count">{events.filter(e=>e.era===era).length} {t.count}</span><span className="era-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
 <section className="section container"><div className="featured"><div className="featured-image"><Image src="/images/manuscript.webp" alt="" width={1200} height={896} sizes="(max-width: 700px) 90vw, 50vw"/></div><div className="featured-copy"><p className="eyebrow">{t.featured} / {featured.date[lang]}</p><h2>{featured.title[lang]}</h2><p>{featured.summary[lang]}</p><Link className="text-link" href={`/${lang}/events/${featured.slug}`}>{t.read} ↗</Link><p className="image-note">{t.imageNote}</p></div></div></section>
 <section className="section container"><div className="section-heading"><div><p className="eyebrow">MAROC / MONDE</p><h2>{t.world}</h2></div><p>{t.worldText}</p></div><div className="story-grid">{[events[2],events[3]].map(e=><EventCard key={e.slug} event={e} lang={lang}/>)}</div></section>
 <section className="section container"><div className="mission"><div><p className="eyebrow">{t.method}</p><h2>{t.collection}</h2><p>{t.collectionText}</p><Link className="text-link" href={`/${lang}/about`}>{t.about} ↗</Link></div><div className="stats"><div><strong>{events.length.toString().padStart(2,'0')}</strong><span>{t.count}</span></div><div><strong>03</strong><span>{t.languages}</span></div></div></div></section></main>;
}
