import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { events, eras, regions, formatDate, isLanguage } from "@/lib/history";
import { copy } from "@/lib/i18n";
import { EventCard } from "@/components/event-card";
export default async function Home({params}: {params: Promise<{lang: string}>}) {
 const {lang} = await params; if (!isLanguage(lang)) notFound(); const t=copy[lang]; const featured=events.find(e=>e.slug==='writing')!;
 const highlights=['egypt-unification','qin-unification','mali-empire','tenochtitlan','endeavour','apollo-11'].map(slug=>events.find(e=>e.slug===slug)!);
 return <main id="content"><section className="hero container"><div className="hero-top world-hero-top"><div><p className="eyebrow line-label">{t.kicker}</p><h1>{t.title}<br/><em>{t.italic}</em></h1><p className="hero-description">{t.intro}</p><div className="hero-actions"><Link className="button primary" href={`/${lang}/explorer`}>{t.start} <span aria-hidden="true">↗</span></Link><Link className="button" href={`/${lang}/events/apollo-11`}>{t.discover}</Link></div></div><div className="hero-range"><span>−300K</span><i>↓</i><strong>2026</strong><small>{t.range}</small></div></div>
 <div className="world-hero-art"><Image src="/illustrations/world.svg" alt="" width={1200} height={620} preload/><div className="world-art-caption"><span className="eyebrow">ATAR / WORLD CHRONICLE</span><p>{t.world}</p><Link className="text-link" href={`/${lang}/explorer`}>{t.explore} ↗</Link></div></div>
 <div className="mini-timeline">{['writing','hijra','gutenberg','industrial-revolution','apollo-11','high-seas-treaty'].map(slug=>{const e=events.find(e=>e.slug===slug)!;return <Link key={e.slug} href={`/${lang}/events/${e.slug}`}><span className="timeline-dot"/><span>{formatDate(e,lang)}</span><small>{e.title[lang]}</small></Link>;})}</div><p className="image-note">{t.timelineNote}</p></section>
 <section id="eras" className="section container"><div className="section-heading"><div><p className="eyebrow">ATAR / {t.eras}</p><h2>{t.eraTitle}</h2></div><p>{t.eraIntro}</p></div><div className="era-grid world-era-grid">{eras.map((era,i) => <Link className="era-card" key={era} href={`/${lang}/explorer?era=${era}`}><span className="eyebrow">0{i+1}</span><h3>{t[era]}</h3><p className="era-range">{t.eraDates[i]}</p><span className="era-count">{events.filter(e=>e.era===era).length} {t.count}</span><span className="era-arrow" aria-hidden="true">↗</span></Link>)}</div></section>
 <section className="section container"><div className="featured"><div className="featured-image"><Image src="/illustrations/ancient.svg" alt="" width={680} height={420}/></div><div className="featured-copy"><p className="eyebrow">{t.featured} / {formatDate(featured,lang)}</p><h2>{featured.title[lang]}</h2><p>{featured.summary[lang]}</p><Link className="text-link" href={`/${lang}/events/${featured.slug}`}>{t.read} ↗</Link></div></div></section>
 <section className="section container"><div className="section-heading"><div><p className="eyebrow">ATAR / {t.region}</p><h2>{t.world}</h2></div><p>{t.worldText}</p></div><nav className="region-links" aria-label={t.region}>{regions.map(region=><Link key={region} href={`/${lang}/explorer?region=${region}`}>{t[region]} ↗</Link>)}</nav><div className="story-grid">{highlights.map(e=><EventCard key={e.slug} event={e} lang={lang}/>)}</div></section>
 <section className="section container"><div className="latest-banner"><div><p className="eyebrow">2026 / {t.latest}</p><h2>{events.at(-1)!.title[lang]}</h2><p>{t.latestText}</p></div><Link className="button" href={`/${lang}/events/high-seas-treaty`}>{t.read} ↗</Link></div></section>
 <section className="section container"><div className="mission"><div><p className="eyebrow">{t.method}</p><h2>{t.collection}</h2><p>{t.collectionText}</p><Link className="text-link" href={`/${lang}/about`}>{t.about} ↗</Link></div><div className="stats"><div><strong>{events.length}</strong><span>{t.count}</span></div><div><strong>06</strong><span>{t.eras}</span></div><div><strong>03</strong><span>{t.languages}</span></div></div></div></section></main>;
}
