import { sceneFor } from "@/lib/journey";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { events, languages, formatDate, editorialUpdated, isLanguage } from "@/lib/history";
import { copy } from "@/lib/i18n";
import { journeyCopy } from "@/lib/journey-copy";
export function generateStaticParams(){return languages.flatMap(lang=>events.map(e=>({lang,slug:e.slug})));}
export async function generateMetadata({params}:{params:Promise<{lang:string;slug:string}>}){const {lang,slug}=await params;const e=events.find(e=>e.slug===slug);return isLanguage(lang)&&e?{title:e.title[lang],description:e.summary[lang]}:{};}
export default async function Page({params}:{params:Promise<{lang:string;slug:string}>}){
 const {lang,slug}=await params;if(!isLanguage(lang))notFound();const index=events.findIndex(e=>e.slug===slug);const e=events[index];if(!e)notFound();const t=copy[lang],j=journeyCopy[lang];const previous=events[index-1],next=events[index+1];const parallel=events.filter(item=>item.slug!==slug&&item.region!==e.region&&item.era===e.era&&Math.abs(item.year-e.year)<=80).sort((a,b)=>Math.abs(a.year-e.year)-Math.abs(b.year-e.year)).slice(0,3);
 return <main id="content" className="film-detail"><section className="film-cover"><Image src={`/images/journey/${sceneFor(e)}.webp`} alt="" fill sizes="100vw" preload/><div className="film-shade"/><div className="film-cover-content"><Link href={`/${lang}?event=${slug}#timecapsule`} className="film-back">← {j.back}</Link><p className="eyebrow">{t[e.era]} / {t[e.region]}</p><p className="film-date">{formatDate(e,lang)}</p><h1>{e.title[lang]}</h1><div className="film-cover-meta"><span>{e.place[lang]}</span><a href="#story">{j.what} ↓</a></div></div><span className="film-art-note">{j.ai} · {t[e.era]}</span></section>
 <nav className="story-nav" aria-label={j.progress}><span>{j.progress}</span><a href="#story">01 / {j.what}</a><a href="#impact">02 / {j.why}</a><a href="#references">03 / {j.source}</a></nav>
 <section id="story" className="film-story container"><span className="story-step">01</span><div><p className="eyebrow">{t[e.theme]} / {formatDate(e,lang)}</p><h2>{j.what}</h2><p className="film-lead">{e.summary[lang]}</p>{e.approximate&&<p className="image-note">{t.approximate}</p>}</div></section>
 <section id="impact" className="film-impact"><div className="container film-impact-inner"><span className="story-step">02</span><div><p className="eyebrow">ATAR / {j.why}</p><h2>{j.why}</h2><p className="film-lead">{e.impact[lang]}</p></div></div></section>
 {parallel.length>0&&<section className="film-parallel container"><p className="eyebrow">{j.elsewhere}</p><h2>{t.meanwhile}</h2><p className="image-note">{j.near}</p><div className="parallel-stories">{parallel.map(item=><Link key={item.slug} href={`/${lang}/events/${item.slug}`}><span className="eyebrow">{formatDate(item,lang)} / {t[item.region]}</span><h3>{item.title[lang]} ↗</h3><p>{item.summary[lang]}</p></Link>)}</div></section>}
 <section id="references" className="film-references container"><span className="story-step">03</span><div><p className="eyebrow">{j.source}</p><h2>{e.sourceName}</h2><a className="journey-button" href={e.source} target="_blank" rel="noopener noreferrer">{t.sourceLink} ↗</a><p className="image-note">{t.verified} {editorialUpdated}</p><p className="image-note">{j.ai} · {t[e.era]}</p><Link className="text-link" href={`/${lang}/about`}>{t.method} ↗</Link></div></section><nav className="event-navigation container" aria-label={t.order}>{previous?<Link href={`/${lang}/events/${previous.slug}`}><span>{t.previous}</span><strong>← {previous.title[lang]}</strong></Link>:<span/>}{next?<Link href={`/${lang}/events/${next.slug}`}><span>{t.next}</span><strong>{next.title[lang]} →</strong></Link>:<span/>}</nav></main>;
}
