import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { events, languages, formatDate, editorialUpdated, isLanguage } from "@/lib/history";
import { copy } from "@/lib/i18n";
import { EventCard } from "@/components/event-card";
export function generateStaticParams(){return languages.flatMap(lang=>events.map(e=>({lang,slug:e.slug})));}
export async function generateMetadata({params}: {params:Promise<{lang:string;slug:string}>}) {const {lang,slug}=await params;const e=events.find(e=>e.slug===slug);return isLanguage(lang)&&e?{title:e.title[lang],description:e.summary[lang]}:{};}
export default async function Page({params}: {params:Promise<{lang:string;slug:string}>}) {
 const {lang,slug}=await params;if(!isLanguage(lang))notFound();const index=events.findIndex(e=>e.slug===slug);const e=events[index];if(!e)notFound();const t=copy[lang];const previous=events[index-1],next=events[index+1];
 const related=events.filter(item=>item.slug!==slug).sort((a,b)=>Math.abs(a.year-e.year)-Math.abs(b.year-e.year)).slice(0,2);
 const parallel=events.filter(item=>item.slug!==slug&&item.region!==e.region&&item.era===e.era&&Math.abs(item.year-e.year)<=80).sort((a,b)=>Math.abs(a.year-e.year)-Math.abs(b.year-e.year)).slice(0,2);
 return <main className="container section" id="content"><Link className="text-link" href={`/${lang}/explorer`}>← {t.back}</Link><div className="detail-heading"><p className="eyebrow">{t[e.era]} / {t[e.theme]}</p><p className="detail-date">{formatDate(e,lang)}</p><h1>{e.title[lang]}</h1><span className="eyebrow">{e.place[lang]} · {t[e.region]}</span>{e.approximate&&<p className="date-note">{t.approximate}</p>}</div><figure className="detail-image"><Image src={`/illustrations/${e.era}.svg`} alt="" width={680} height={420}/><figcaption className="image-note">{t.imageNote}</figcaption></figure><div className="detail-grid"><article><div className="brief"><p className="eyebrow">{t.happened}</p><p>{e.summary[lang]}</p></div><h2>{t.impact}</h2><p className="impact-text">{e.impact[lang]}</p>{parallel.length>0&&<section className="parallel"><h2>{t.meanwhile}</h2><p className="image-note">{t.meanwhileNote}</p>{parallel.map(item=><Link key={item.slug} className="parallel-link" href={`/${lang}/events/${item.slug}`}><span>{formatDate(item,lang)} · {t[item.region]}</span><h3>{item.title[lang]} ↗</h3></Link>)}</section>}</article><aside className="source-panel"><p className="eyebrow">{t.source}</p><h3>{e.sourceName}</h3><a className="text-link" href={e.source} target="_blank" rel="noopener noreferrer">{t.sourceLink} ↗</a><p className="image-note">{t.verified} {editorialUpdated}</p><dl><dt>{t.date}</dt><dd>{formatDate(e,lang)}</dd><dt>{t.place}</dt><dd>{e.place[lang]}</dd><dt>{t.region}</dt><dd>{t[e.region]}</dd></dl><Link className="text-link" href={`/${lang}/about`}>{t.method} ↗</Link></aside></div><nav className="event-navigation" aria-label={t.order}>{previous?<Link href={`/${lang}/events/${previous.slug}`}><span>{t.previous}</span><strong>← {previous.title[lang]}</strong></Link>:<span/>}{next?<Link href={`/${lang}/events/${next.slug}`}><span>{t.next}</span><strong>{next.title[lang]} →</strong></Link>:<span/>}</nav><section className="section"><h2>{t.related}</h2><div className="story-grid">{related.map(item=><EventCard key={item.slug} event={item} lang={lang}/>)}</div></section></main>;
}
