"use client";
import { useEffect, useState } from "react";
import { eras, regions, themes, type Language } from "@/lib/history";
import { premiumCopy } from "@/lib/premium-copy";
import { copy } from "@/lib/i18n";
import { exploreEvents, invalidYears, type Filters } from "@/lib/explore";
import { EventCard } from "./event-card";
export function Explorer({lang,initial}: {lang: Language; initial: Filters}) {
 const t=copy[lang];const p=premiumCopy[lang]; const [filters,setFilters]=useState(initial);const [limit,setLimit]=useState(12);
 const filtered=exploreEvents(lang,filters);const badRange=invalidYears(filters.from,filters.to);
 function update(key:keyof Filters,value:string|boolean){setFilters(current=>({...current,[key]:value}));setLimit(12);}
 function reset(){setFilters({era:'all',region:'all',theme:'all',query:'',from:'',to:'',desc:false});setLimit(12);}
 useEffect(()=>{const params=new URLSearchParams();for(const [key,value] of Object.entries(filters)){if(value&&value!=='all')params.set(key,String(value));}const url=params.size?`?${params.toString()}`:window.location.pathname;window.history.replaceState(null,'',url);},[filters]);
 return <main className="container explorer section" id="content"><p className="eyebrow">ATAR / {t.explore}</p><h1>{t.explorerTitle}</h1><p className="hero-description">{t.explorerIntro}</p><div className="filters"><label className="search-label"><span className="sr-only">{t.search}</span><input type="search" value={filters.query} onChange={e=>update('query',e.target.value)} placeholder={t.search}/></label><div className="filter-row"><span className="filter-label">{t.eras}</span>{(['all',...eras] as const).map(key=><button key={key} aria-pressed={filters.era===key} onClick={()=>update('era',key)}>{t[key]}</button>)}</div><details className="advanced-filters" open={Boolean(initial.region!=='all'||initial.theme!=='all'||initial.from||initial.to)}><summary>{p.filters} +</summary><div className="filter-selects"><label>{t.region}<select value={filters.region} onChange={e=>update('region',e.target.value)}>{(['all',...regions] as const).map(key=><option key={key} value={key}>{t[key]}</option>)}</select></label><label>{t.themes}<select value={filters.theme} onChange={e=>update('theme',e.target.value)}>{(['all',...themes] as const).map(key=><option key={key} value={key}>{t[key]}</option>)}</select></label><label>{t.fromYear}<input type="number" step="1" value={filters.from} onChange={e=>update('from',e.target.value)} placeholder="−3200" aria-describedby="year-hint" aria-invalid={badRange}/></label><label>{t.toYear}<input type="number" step="1" value={filters.to} onChange={e=>update('to',e.target.value)} placeholder="2026" aria-describedby="year-hint" aria-invalid={badRange}/></label></div><p className="image-note" id="year-hint">{t.yearHint}</p></details>{badRange&&<p role="alert" className="range-error">{t.invalidRange}</p>}<div className="filter-bottom"><span role="status">{filtered.length} {t.results}</span><label><span className="sr-only">{t.order}</span><select value={filters.desc?'desc':'asc'} onChange={e=>update('desc',e.target.value==='desc')}><option value="asc">{t.oldest}</option><option value="desc">{t.newest}</option></select></label><button onClick={reset}>{t.reset}</button></div></div><p className="image-note">{t.timelineNote}</p><div className="timeline-list">{filtered.slice(0,limit).map(e=><div className="timeline-entry" key={e.slug}><span className="timeline-dot"/><EventCard event={e} lang={lang}/></div>)}</div>{filtered.length===0&&!badRange&&<div className="empty"><h2>{t.empty}</h2><button className="button" onClick={reset}>{t.reset}</button></div>}{filtered.length>0&&<div className="load-more"><p aria-live="polite">{t.showing} {Math.min(limit,filtered.length)} {t.of} {filtered.length}</p>{limit<filtered.length&&<button className="button" onClick={()=>setLimit(limit+12)}>{t.readMore} ↓</button>}</div>}</main>;
}
