"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { languages, type Language } from "@/lib/history";
import { useTheme } from "@/lib/theme";
import { compareCopy } from "@/lib/compare-copy";
import { premiumCopy } from "@/lib/premium-copy";
import { copy } from "@/lib/i18n";
import { Icon } from "./icon";
export function Shell({lang,children}:{lang:Language;children:React.ReactNode}){
 const t=copy[lang],c=compareCopy[lang],p=premiumCopy[lang];const pathname=usePathname();const {light,toggle}=useTheme();const [open,setOpen]=useState(false);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';},[lang]);
 useEffect(()=>{function dismiss(event:PointerEvent){document.querySelectorAll('.locale-picker[open],.time-options[open]').forEach(item=>{if(!item.contains(event.target as Node))item.removeAttribute('open');});}function escape(event:KeyboardEvent){if(event.key==='Escape'){document.querySelectorAll('.locale-picker[open],.time-options[open]').forEach(item=>item.removeAttribute('open'));setOpen(false);}}document.addEventListener('pointerdown',dismiss);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',dismiss);document.removeEventListener('keydown',escape);};},[]);
 const links=[[t.explore,`/${lang}/explorer`],['Atlas',`/${lang}#atlas`],[c.nav,`/${lang}/compare`]];
 return <div className={`site ${light?'light':''}`} lang={lang} dir={lang==='ar'?'rtl':'ltr'}><a className="skip" href="#content">{t.skip}</a><header className="header"><div className="header-inner"><Link className="brand" href={`/${lang}`} aria-label="ATAR"><span>ATAR</span><i/><span lang="ar">أثر</span></Link><nav className="desktop-nav" aria-label={t.menu}>{links.map(([label,url])=><Link key={url} href={url} aria-current={pathname===url?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><details className="locale-picker"><summary aria-label={t.languageLabel}><Icon name="globe"/><span>{lang.toUpperCase()}</span><Icon name="chevron"/></summary><nav className="lang-switch" aria-label={t.languageLabel}>{languages.map(l=><Link key={l} href={pathname.replace(/^\/(fr|en|ar)(?=\/|$)/,`/${l}`)} aria-current={l===lang?'page':undefined} hrefLang={l} onClick={event=>{if(window.location.search){event.preventDefault();window.location.assign(pathname.replace(/^\/(fr|en|ar)(?=\/|$)/,`/${l}`)+window.location.search);}else{event.currentTarget.closest('details')?.removeAttribute('open');}}}><span>{l==='fr'?'Français':l==='en'?'English':'العربية'}</span><small>{l.toUpperCase()}</small></Link>)}</nav></details><button className="icon-button theme-toggle" onClick={toggle} aria-label={t.theme}><Icon name={light?'moon':'sun'}/></button><button className="mobile-toggle icon-button" onClick={()=>setOpen(!open)} aria-label={t.menu} aria-expanded={open} aria-controls="mobile-menu"><Icon name={open?'close':'menu'}/></button></div></div>{open&&<nav id="mobile-menu" className="mobile-nav" aria-label={t.menu}>{links.map(([label,url])=><Link key={url} href={url} onClick={()=>setOpen(false)}>{label}<Icon name="arrow"/></Link>)}<Link href={`/${lang}/about`} onClick={()=>setOpen(false)}>{t.about}<Icon name="arrow"/></Link></nav>}</header>{children}<footer className="footer container"><div className="footer-top"><div><p className="eyebrow">ATAR / {p.signature}</p><h2>{p.footer}</h2></div><Link className="round-arrow" href={`/${lang}/explorer`} aria-label={t.explore}><Icon name="arrow" width="28" height="28"/></Link></div><div className="footer-wordmark" aria-hidden="true">ATAR<span>↗</span></div><div className="footer-bottom"><p>{p.footerNote}</p><nav aria-label={t.menu}><Link href={`/${lang}/about`}>{t.method}</Link><Link href={`/${lang}/compare`}>{c.nav}</Link><span>© {new Date().getFullYear()} ATAR</span></nav></div></footer></div>;
}
