"use client";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { events, eras, regions, formatDate, type Language, type Region } from "@/lib/history";
import { copy } from "@/lib/i18n";
import { journeyCopy } from "@/lib/journey-copy";
import { premiumCopy } from "@/lib/premium-copy";
import { sceneFor, nearestEvent, project, regionPoints } from "@/lib/journey";
import { comparisonHref } from "@/lib/compare";
import { compareCopy } from "@/lib/compare-copy";
import { landPath } from "@/lib/world-land";
import { Icon } from "./icon";
export function TimeMachine({lang,initialSlug,intro}:{lang:Language;initialSlug:string;intro:boolean}){
 const t=copy[lang],j=journeyCopy[lang],c=compareCopy[lang],p=premiumCopy[lang];
 const [index,setIndex]=useState(()=>Math.max(0,events.findIndex(e=>e.slug===initialSlug)));
 const [active,setActive]=useState(!intro),[playing,setPlaying]=useState(false);
 const [region,setRegion]=useState<Region>(()=>events.find(e=>e.slug===initialSlug)?.region??'middleEast');
 const [year,setYear]=useState(''),[error,setError]=useState(false);const gallery=useRef<HTMLDivElement>(null);
 const current=events[index],atEra=events.filter(e=>e.era===current.era);
 const panel=atEra.filter(e=>e.region===region).sort((a,b)=>Math.abs(a.year-current.year)-Math.abs(b.year-current.year));
 const scene=active?sceneFor(current):'time-portal';
 useEffect(()=>{if(!active)return;const url=new URL(window.location.href);url.searchParams.set('event',events[index].slug);window.history.replaceState(null,'',url.pathname+url.search+url.hash);},[index,active]);
 useEffect(()=>{if(!playing)return;const timer=setTimeout(()=>{const next=(index+1)%events.length;setIndex(next);setRegion(events[next].region);},6500);return()=>clearTimeout(timer);},[playing,index]);
 function choose(i:number){setIndex(i);setRegion(events[i].region);setActive(true);setPlaying(false);setError(false);}
 function jump(e:React.FormEvent){e.preventDefault();const number=Number(year);if(!year.trim()||!Number.isInteger(number)||number===0||number<events[0].year||number>2026){setError(true);return;}choose(nearestEvent(number));}
 function era(eraIndex:number,scroll=false){choose(events.findIndex(e=>e.era===eras[eraIndex]));if(scroll)document.getElementById('timecapsule')?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 function galleryScroll(direction:number){gallery.current?.scrollBy({left:(lang==='ar'?-1:1)*direction*gallery.current.clientWidth*.75,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}
 return <div className="experience"><section className={`time-stage ${active?'is-journey':'is-intro'}`} id="timecapsule" aria-label={j.voyage}>
 <div className="hero-frame"><div className="scene-backdrop" key={`scene-${scene}`}><Image src={`/images/journey/${scene}.webp`} alt="" fill sizes="(max-width:700px) 100vw, 96vw" preload/></div><div className="scene-shade"/>
 <div className="stage-top"><span><i className="status-dot"/>{p.signature}</span><span>{active?`${String(index+1).padStart(2,'0')} / ${events.length}`:j.years}</span></div>
 <div className="hero-main" key={active?`story-${current.slug}`:'intro'}><p className="eyebrow">{active?`${t[current.era]} · ${formatDate(current,lang)}`:'ATAR / WORLD HISTORY'}</p><h1>{active?current.title[lang]:<>{p.title}<br/><em>{p.italic}</em></>}</h1><p className="hero-copy">{active?current.summary[lang]:p.intro}</p>{active?<Link className="journey-button primary" href={`/${lang}/events/${current.slug}`}>{j.read}<Icon name="arrow"/></Link>:<button className="journey-button primary" onClick={()=>choose(0)}>{p.start}<Icon name="arrow"/></button>}</div>
 {!active&&<Link className="hero-feature" href={`/${lang}/events/${current.slug}`}><Image src={`/images/journey/${sceneFor(current)}.webp`} alt="" width={100} height={110}/><div><span>{p.featured} / {formatDate(current,lang)}</span><h2>{current.title[lang]}</h2></div><Icon name="arrow"/></Link>}
 <div className="scene-bottom"><span>{active?current.place[lang]:j.voyage}</span><span>{j.ai}</span></div></div>
 <div className="time-dock"><div className="time-dock-main"><div className="transport"><button onClick={()=>choose(Math.max(0,index-1))} disabled={active&&index===0} aria-label={j.prev}><Icon name="left"/></button><button onClick={()=>{setActive(true);setPlaying(!playing);}} aria-label={playing?j.pause:j.play} aria-pressed={playing}><Icon name={playing?'pause':'play'}/></button><button onClick={()=>choose(Math.min(events.length-1,index+1))} disabled={index===events.length-1} aria-label={j.next}><Icon name="right"/></button></div><div className="time-track"><div className="track-labels"><span>{active?formatDate(current,lang):p.start}</span><small>{j.range}</small></div><input type="range" min="0" max={events.length-1} value={index} onChange={e=>choose(Number(e.target.value))} aria-label={j.range} aria-valuetext={`${formatDate(current,lang)} — ${current.title[lang]}`}/></div><details className="time-options"><summary>{j.year}<Icon name="chevron"/></summary><div className="time-options-panel dock-foot"><form onSubmit={jump}><label htmlFor="jump-year">{j.year}</label><div><input id="jump-year" type="number" step="1" value={year} onChange={e=>{setYear(e.target.value);setError(false);}} placeholder="−3200" aria-describedby="jump-note" aria-invalid={error}/><button type="submit" aria-label={j.jump}><Icon name="right"/></button></div></form>{error&&<p className="jump-error" role="alert">{j.invalid}</p>}<p id="jump-note" className="image-note">{j.jumpNote}</p></div></details></div><div className="dock-eras">{eras.map((item,i)=><button key={item} onClick={()=>era(i)} aria-pressed={active&&current.era===item}>{t[item]}</button>)}</div></div>
 </section>
 <section className="chapter-section container" id="eras"><div className="section-heading"><div><p className="eyebrow">01 / {j.chapter}</p><h2>{p.eras}</h2></div><div className="gallery-controls"><button className="icon-button" onClick={()=>galleryScroll(-1)} aria-label={p.galleryPrev}><Icon name="left"/></button><button className="icon-button" onClick={()=>galleryScroll(1)} aria-label={p.galleryNext}><Icon name="right"/></button></div></div><div className="cinema-chapters" ref={gallery} role="region" aria-label={p.eras} tabIndex={0}>{eras.map((item,i)=><button className="cinema-chapter" key={item} onClick={()=>era(i,true)} aria-pressed={active&&current.era===item}><Image src={`/images/journey/${item}.webp`} alt="" fill sizes="(max-width:700px) 75vw, 320px"/><div className="chapter-shade"/><span className="chapter-number">0{i+1}</span><div className="chapter-caption"><p>{t.eraDates[i]}</p><h3>{t[item]}</h3><span>{j.open}<Icon name="arrow"/></span></div></button>)}</div><div className="gallery-bottom"><p>{p.erasIntro}</p><span>{j.ai}</span></div></section>
 <section className="atlas-section container" id="atlas"><div className="section-heading"><div><p className="eyebrow">02 / ATLAS</p><h2>{p.mapIntro}</h2></div><label className="atlas-era-select"><span className="sr-only">{p.era}</span><select value={current.era} onChange={e=>era(eras.indexOf(e.target.value as typeof eras[number]))}>{eras.map(item=><option key={item} value={item}>{t[item]}</option>)}</select></label></div><div className="atlas-layout"><div className="atlas-map"><svg viewBox="0 0 720 360" role="img" aria-label={j.atlas}><defs><pattern id="atlas-grid" width="60" height="60" patternUnits="userSpaceOnUse"><path d="M60 0H0V60" fill="none" stroke="currentColor" strokeOpacity=".05"/></pattern></defs><rect width="720" height="360" fill="url(#atlas-grid)"/><path d={landPath} className="map-land"/></svg>{regions.map(r=>{const[x,y]=project(regionPoints[r]);const count=atEra.filter(e=>e.region===r).length;return <button key={r} style={{left:`${x/720*100}%`,top:`${y/360*100}%`}} className={`map-pin ${region===r?'selected':''} ${count?'':'quiet'}`} onClick={()=>setRegion(r)} aria-label={`${t[r]} — ${count} ${t.results}`} aria-pressed={region===r}><i/><span>{t[r]} <b>{count}</b></span></button>;})}<span className="map-watermark" aria-hidden="true">ATAR / WORLD ATLAS</span></div><div className="atlas-stories" aria-live="polite"><p className="eyebrow">{t[region]} / {t[current.era]}</p><h3>{j.elsewhere}</h3>{panel.length?panel.slice(0,2).map(event=><Link className="atlas-story" key={event.slug} href={`/${lang}/events/${event.slug}`}><span>{formatDate(event,lang)}</span><h4>{event.title[lang]}<Icon name="arrow"/></h4></Link>):<p className="atlas-empty">{j.empty}</p>}<div className="atlas-actions"><Link className="text-link" href={`/${lang}/explorer?era=${current.era}&region=${region}`}>{j.archive}<Icon name="arrow"/></Link><Link className="atlas-compare-link" href={comparisonHref(lang,current.slug,panel.find(e=>e.slug!==current.slug)?.slug)}>{c.nav}<Icon name="arrow"/></Link></div></div></div><div className="atlas-bottom"><p>{p.atlasIntro}</p><details><summary>{p.mapInfo}</summary><p>{j.map} {j.near}</p></details></div></section></div>;
}
